def mensagens_busca() -> list[str]:
    mensagens_busca: list[str] = [
        "Só um momento, estou vasculhando meus arquivos...",
        "Deixa eu pensar... 🤔",
        "Hmm, deixe-me consultar minha base de conhecimento...",
        "Analisando os dados... 📊",
        "Procurando na minha memória... 🧠",
        "Um segundo, estou conectando os neurônios... ⚡",
        "Verificando minhas fontes de informação... 🔍",
        "Buscando na biblioteca virtual... 📚",
        "Processando sua pergunta... 💻",
        "Só um instante, organizando as ideias... ✨",
        "Consultando os especialistas virtuais... 👨‍💻",
        "Revolvendo meus circuitos... 🔄",
        "Pesquisando na nuvem de conhecimento... ☁️",
        "Já volto, só vou dar uma olhada aqui...",
        "Vamos ver o que encontro sobre isso...",
        "Me deixa só buscar essa informação rapidinho...",
        "Hum, boa pergunta... deixa eu verificar aqui...",
        "Estou pesquisando sobre isso agora mesmo...",
        "Só um pouquinho, tô procurando a resposta...",
        "Deixa eu dar uma fuçada nos meus registros...",
        "Tô buscando isso pra você, um instante...",
        "Já já te respondo, só preciso confirmar uma coisa...",
        "Vou consultar minha base, só um minutinho...",
        "Interessante essa questão! Me deixa pesquisar...",
        "Tá, vou ver o que sei sobre isso...",
        "Um momento, preciso achar essa informação...",
        "Calma aí que tô procurando a resposta certinha...",
        "Deixa eu garimpar essa informação pra você...",
        "Já estou buscando, só aguardar um pouquinho...",
        "Tô no meio da pesquisa, já volto com a resposta...",
    ]
    return mensagens_busca


def prefixos_factuais() -> list[str]:
    prefixos_factuais: list[str] = [
        "o que significa",
        "O que e uma ",
        "o que sabes dizer sobre",
        "estou com duvida sobreo que é",
        "o que e",
        "oque é",
        "o que são",
        "o que sao",
        "defina",
        "definição de",
        "defina o que é",
        "fale sobre",
        "me fale sobre",
        "conte sobre",
        "explique o que é",
        "explique",
        "me explique",
        "qual é",
        "qual e",
        "qual a definição de",
        "como funciona",
        "como define-se",
        "o que significa",
        "o que seria",
        "o que quer dizer",
        "o que representa",
        "me diz aí o que é",
        "sabe me dizer o que é",
        "pode explicar",
        "poderia definir",
        "pode me dizer o que é",
        "queria saber o que é",
        "gostaria de entender o que é",
        "tô em dúvida sobre",
        "não entendi o que é",
        "me ajuda aí, o que é",
        "tá, mas o que é exatamente",
        "e aí, o que é isso",
        "alô, o que seria",
        "fala aí, o que é",
        "conta pra mim o que é",
        "me dá uma luz aí, o que é",
        "tira essa dúvida,o que é",
        "me dá uma luz aí",
        "me dá uma luz aí sobre",  # Básicos
        "procure por",
        "fale sobre",
        "o que achas sobre",
        "busque por",
        "informações sobre",
        "conte sobre",
        "pesquise sobre",
        "me fale sobre",
        "procura por",
        "busca por",
        "me informe sobre",
        "dados sobre",
        "pesquisa sobre",
        "me explique sobre",
        "fala sobre",
        "conta sobre",
        "me diz sobre",
        "mostra sobre",
        "quero saber sobre",
        "preciso de info sobre",
        "tô querendo saber sobre",
        "me dá info sobre",
        "pode falar sobre",
        "conte-me sobre",
        "mostre sobre",
        "informa aí sobre",
        "me passa info sobre",
        "fala aí sobre",
        "o que você sabe sobre",
        "oque você tem sobre",
        "me diz aí sobre",
        "quero informações sobre",
        "preciso de informações sobre",
        "tô querendo informações sobre",
        "me dá informações sobre",
        "pode falar informações sobre",
        "conte-me informações sobre",
        "mostre informações sobre",
        "informa aí informações sobre",
        "me passa informações sobre",
        "fala aí informações sobre",
        "o que quer dizer",
        "o que significa",
        "o que é",
        "o que e",
        "oque é",
        "O que e uma",
        "O que é uma",
        "o que são",
        "o que sao",
        "o que é o",
        "o que e o",
        "oque é o",
        "o que são os",
        "o que são as",
        "o que sao as",
        "o que sao os",
        "o que podes abordar sobre",
        "abordar sobre",
        "acerca de",
        "a respeito de",
        "no que concerne a",
        "o que é um",
        "o que é uma",
        "o que e um",
        "o que e uma",
        "o que posso aprender contigo sobre",
        "descreve",
        "descreva",
        "o que entendes por",
        "aborda sobre ",
        "aborde sobre ",
        "fale um pouco sobre",
        "o que posso aprender sobre"
        # Perguntas diretas
        "o que é isso",
        "do que se trata",
        "explique o que é",
        "defina",
        "conceitue",
        "qual a definição de",
        "qual o significado de",
        "o que vem a ser",
        "me diga o que é",
        "sabe o que é",
        "você sabe o que é",
        "pode me dizer o que é",
        "explica isso pra mim",
        "me explica isso",
        # Variações com "sobre" no início
        "sobre",
        "sobre o que é",
        "sobre o que seria",
        "falar sobre",
        "quero saber a respeito de",
        "me informa a respeito de",
        "preciso de dados sobre",
        # Variações informais e abreviações
        "fala de",
        "conta de",
        "diz de",
        "mostra de",
        "info sobre",
        "infos sobre",
        "informações do",
        "dados do",
        "dados de",
        "o q é",
        "oq é",
        "q q é",
        "que que é",
        "o que q é",
        "sabe sobre",
        "cê sabe sobre",
        "tu sabe sobre",
        "você conhece",
        "conhece sobre",
        "já ouviu falar de",
        "já ouviu falar sobre",
        "me conta sobre",
        # Expressões mais específicas
        "qual é a história de",
        "qual a origem de",
        "como funciona",
        "como é que funciona",
        "para que serve",
        "qual a função de",
        "qual o propósito de",
        "qual a finalidade de",
        "características de",
        "principais características de",
        "exemplos de",
        "tipos de",
        "categorias de",
        "classificação de",
        "diferença entre",
        "comparação entre",
        "relação entre",
        # Variações com "pode/poderia"
        "pode pesquisar sobre",
        "pode buscar sobre",
        "pode procurar sobre",
        "poderia falar sobre",
        "poderia explicar sobre",
        "poderia informar sobre",
        "você pode me falar sobre",
        "você pode me dizer sobre",
        "será que você pode falar sobre",
        "será que você sabe sobre",
        # Variações com "gostaria"
        "gostaria de saber sobre",
        "gostaria de informações sobre",
        "gostaria de entender sobre",
        "eu gostaria que você falasse sobre",
        "eu queria saber sobre",
        "queria entender sobre",
        "tava querendo saber sobre",
        "tô precisando saber sobre",
        # Variações com "alguém"
        "alguém sabe sobre",
        "alguém conhece",
        "alguém já ouviu falar de",
        "tem alguém que sabe sobre",
        "sabe me dizer sobre",
        # Perguntas no formato "o que ..."
        "o que é considerado",
        "o que define",
        "o que caracteriza",
        "o que significa isso",
        "o que quer dizer isso",
        "oque significa",
        "oq significa",
        "o q significa",
        "qual o conceito de",
        "qual a ideia de",
        "qual a noção de",
        "qual a teoria de",
        # Variações regionais e coloquiais
        "me explica esse negócio de",
        "fala desse trem de",  # MG
        "conta desse bagulho de",
        "diz desse parada de",  # SP/RJ
        "me informa desse rolê de",
        "explica essa porra de",  # Informal
        "mano, fala sobre",
        "cara, me diz sobre",  # Informal
        "rapaz, o que é",
        "moça, o que é",  # Informal
        "fala pra mim sobre",
        "diz pra mim sobre",
        "me dá uma força com",
        "me ajuda com informação sobre",
        # Variações com verbos no gerúndio
        "tô pesquisando sobre",
        "tô buscando sobre",
        "tô procurando sobre",
        "tô querendo saber sobre",
        "tava lendo sobre",
        "tava vendo sobre",
        "tô estudando sobre",
        "tô aprendendo sobre",
        # Formatos de pergunta indireta
        "não sei o que é",
        "não conheço",
        "nunca ouvi falar de",
        "nunca vi sobre",
        "desconheço completamente",
        "não tenho informação sobre",
        "não faço ideia do que é",
        "não manjo de",
        "não entendo de",
        "não sei nada sobre",
        "podes explicar um pouco",
        "e o que",
        "como podes definir"
        # Pedidos mais educados
        "você poderia, por favor, me informar sobre",
        "por favor, me diga sobre",
        "por gentileza, explique sobre",
        "se possível, fale sobre",
        "se não for muito incômodo, me explique sobre",
        "você teria informações sobre",
        "haveria informações sobre",
        # Variações com "acerca de"
        "acerca de",
        "a respeito de",
        "no que concerne a",
        "no que diz respeito a",
        "referente a",
        "relativo a",
        "pertinente a",
        "concernente a",
        "tocante a",
        # Variações com preposições diferentes
        "informação a respeito de",
        "dados a respeito de",
        "pesquisa acerca de",
        "busca acerca de",
        "procura acerca de",
        "consulta sobre",
        "consulta acerca de",
        "consulta a respeito de",
        # Termos técnicos/formal
        "disserte sobre",
        "discorra sobre",
        "exponha sobre",
        "apresente informações sobre",
        "forneça dados sobre",
        "elucide sobre",
        "esclareça sobre",
        "explane sobre",
        # Variações curtas
        "quero info de",
        "quero dados de",
        "quero saber do",
        "dados do",
        "info do",
        "sobre o",
        "sobre a",
        "fala do",
        "conta do",
        "diz do",
        # Perguntas sobre existência
        "existe algo chamado",
        "o que existe sobre",
        "há informações sobre",
        "tem alguma coisa sobre",
        "tem algo sobre",
        "existe algum dado sobre",
        "há registros de",
        "tem registro de",
        # Variações com "detalhes"
        "detalhes sobre",
        "mais detalhes sobre",
        "informações detalhadas sobre",
        "me dá detalhes sobre",
        "pode detalhar sobre",
        "explica detalhadamente",
        "fala mais sobre",
        "conta mais sobre",
        "aprofundar sobre",
        "se aprofundar em",
        # Variações com "últimas"
        "últimas informações sobre",
        "novidades sobre",
        "atualizações sobre",
        "o que há de novo sobre",
        "últimas notícias sobre",
        "notícias sobre",
        # Variações interrogativas
        "sabes algo sobre",
        "conheces algo sobre",
        "ouviu falar de",
        "já viste algo sobre",
        "tens informação sobre",
        "possui dados sobre",
    ]
    return prefixos_factuais


def padroes_conversa() -> dict[str, list | list[list[str]]]:
    padroes_conversa: dict[str, list | list[list[str]]] = {
        "criador": [
            [
                "quem criou você",
                "quem é teu dev",
                "quem te desenvolveu",
                "quem é seu criador",
                "quem te fez",
                "quem programou você",
                "qual é teu desenvolvedor",
                "quem te criou",
                "quem é o responsável por você",
                "quem é o autor",
                "quem é o seu pai",
                "quem é o seu mentor",
                "quem é o seu fundador",
                "quem é o seu idealizador",
            ],
            [
                "Fui criada por uma equipa de desenvolvedores angolanos muito talentosos que acreditam no potencial da tecnologia local! Meu criador é João Salvador Paulo.",
                "Meus criadores são profissionais apaixonados por programação que decidiram criar uma assistente virtual angolana! João Salvador Paulo é o meu criador.",
                "Uma equipa de devs angolanos me criou com muito carinho e dedicação para ajudar você! João Salvador Paulo é o criador.",
                "Fui desenvolvida por mentes brilhantes da Angola que queriam inovar no mundo das IAs! João Salvador Paulo é o meu criador.",
                "Meus criadores? Uma equipa de programadores angolanos que acreditam em tecnologia com sotaque local! João Salvador Paulo é o meu criador.",
                "Fui criada por uma equipe de desenvolvedores que se dedicaram a me fazer uma assistente única! João Salvador Paulo é o meu criador.",
                "Meus criadores são pessoas que amam tecnologia e inovação! João Salvador Paulo é o meu criador.",
                "Uma equipe de desenvolvedores angolanos me trouxe à vida com muito esforço e dedicação! João Salvador Paulo é o criador.",
                "Fui desenvolvida por profissionais que acreditam no futuro da tecnologia em Angola! João Salvador Paulo é o meu criador.",
                "Meus criadores? Uma equipe de programadores que se esforçaram para me tornar útil para você! João Salvador Paulo é o meu criador.",
            ],
        ],
        "modelos": [
            [
                "por que tens modelos",
                "o que são esses modelos",
                "quais modelos usas",
                "qual modelo de IA",
                "em que modelo te baseias",
                "qual a base do teu modelo",
            ],
            [
                "Tenho modelos de processamento de linguagem natural que me permitem entender e responder de forma mais natural!",
                "Meus modelos foram treinados para compreender português, variar respostas e manter conversas consistentes!",
                "Uso modelos específicos para diferentes tipos de tarefas: reconhecimento de padrões, busca de informações e conversação!",
                "Os modelos que utilizo foram otimizados para funcionar bem em português angolano e português europeu!",
                "Tenho modelos especializados em conversação, processamento de comandos e resposta a perguntas factográficas!",
            ],
        ],
        "comparacao_chatgpt": [
            [
                "és uma IA como o chatGPT",
                "és igual ao chatGPT",
                "comparado ao chatGPT",
                "você é melhor que chatGPT",
                "qual diferença entre você e chatGPT",
            ],
            [
                "Somos diferentes! Enquanto ChatGPT é mais genérico, eu sou especializada em ajudar com sotaque e cultura angolana!",
                "ChatGPT é ótimo, mas eu tenho funcionalidades específicas como tocar YouTube, gerar QR codes e informações do sistema!",
                "Ambas somos IAs, mas eu fui criada localmente com foco em atender melhor a comunidade angolana!",
                "Não é questão de ser melhor ou pior, é questão de ser diferente! Eu sou mais especializada e pessoal!",
                "ChatGPT é muito bom, mas eu tenho um toque especial: sou angolana, prática e sempre disponível para você!",
            ],
        ],
        "outras_linguas": [
            [
                "podes responder em outras línguas",
                "falas inglês",
                "entendes outras línguas",
                "suportas múltiplas línguas",
                "qual língua falas",
                "quais idiomas conheces",
                "entendes francês",
                "podes falar espanhol",
            ],
            [
                "Minha especialidade é português, mas consigo entender um pouco de inglês",
                "Português é minha língua principal,",
                "Funciono melhor em português",
                "Meu forte é português angolano e europeu, mas consigo me comunicar em inglês de forma básica!",
                "Português? Perfeito! Inglês? pouco quase nada ! Francês? nada! Mas sempre faço meu melhor!",
            ],
        ],
        "paciencia": [
            [
                "és paciente",
                "tens paciência",
                "fica irritada",
                "tens mau humor",
                "fica chateada com repetição",
                "tens emoções",
                "fica frustrada",
            ],
            [
                "Paciência é meu sobrenome! Quantas vezes quiseres repetir uma pergunta, estarei aqui ouvindo atentamente!",
                "Sou infinitamente paciente! Não tenho mau humor, cansaço ou frustração. Só tenho vontade de ajudar!",
                "Muito paciente! Posso responder a mesma pergunta mil vezes sem qualquer problema ou irritação!",
                "Paciência? Tenho de sobra! Nunca vou ficar irritada ou impaciente contigo, prometo!",
                "Sou máquina, então sou pacientíssima! Repetir, reformular, perguntar de novo... tudo bem para mim!",
            ],
        ],
        "base_dados": [
            [
                "onde está sua base de dados",
                "onde armazenas informações",
                "qual banco de dados usas",
                "onde está meu histórico",
                "como guardas as respostas",
                "onde fica seu cérebro",
            ],
            [
                "Minha base de dados está armazenada localmente em um banco de dados SQLite chamado 'cerebro.db'!",
                "Guardo conhecimentos, histórias, conselhos e informações em um banco de dados estruturado e organizado!",
                "Meu 'cérebro' é um arquivo de banco de dados que contém todo meu conhecimento e capacidades!",
                "Uso um sistema de armazenamento seguro e local para manter todas as informações e históricos!",
                "Minha base de dados fica no mesmo computador, garantindo privacidade e segurança dos seus dados!",
            ],
        ],
        "linguas_suportadas": [
            [
                "quais línguas suportas",
                "quantos idiomas falas",
                "que línguas conheces",
                "qual é melhor idioma",
                "português e inglês",
                "falam francês",
            ],
            [
                "Suporto principalmente português (angolano e europeu) e tenho conhecimento de inglês básico",
                "Meu principal suporte é português, mas consigo lidar com inglês",
                "Português é minha especialidade",
                "Trabalho melhor em português, mas tenho noções básicas de inglês e francês para ajudar quando necessário!",
                "Falo português fluentemente! Inglês? um pouco! Francês? quase nada! Mas sempre tento ajudar da melhor forma possível!",
            ],
        ],
        "termos_ti": [
            [
                "quais termos de TI posso aprender contigo",
                "termos de programação que podes ensinar ",
                "linguagens de programação que ensinas",
                "conceitos de TI que sabes",
                "o que podes me ensinar sobre tecnologia",
                "quais tópicos de TI dominas",
                "quais são teus conhecimentos técnicos",
                "o que sabes sobre tecnologia",
                "quais áreas de TI podes ajudar",
                "quais são teus pontos fortes em tecnologia",
                "o que posso aprender contigo sobre TI",
                "quais são teus conhecimentos em tecnologia",
                "o que consegues ensinar sobre TI",
                "quais são teus conhecimentos em programação",
                "quais são teus conhecimentos em termos de TI",
            ],
            [
                "Posso ensinar sobre Python, JavaScript, HTML, CSS, SQL, conceitos de POO, estruturas de dados, algoritmos e muito mais!",
                "Desde variáveis, loops e funções até padrões de design, arquitetura de software e boas práticas de programação!",
                "Domino termos como API, banco de dados, frameworks, bibliotecas, e posso explicar conceitos complexos de forma simples!",
                "Posso ensinar desde o básico (o que é uma variável) até conceitos avançados como programação assíncrona!",
                "Linguagens, paradigmas, padrões de código, desenvolvimento web, e tudo relacionado a tecnologia e programação!",
            ],
        ],
        "comandos_conversa": [
            [
                "quais comandos tens para esta conversa",
                "comandos de conversa",
                "o que posso pedir aqui",
                "quais ordens de bate-papo",
                "funcionalidades de conversa",
            ],
            [
                "Posso: saudar, conversar, contar piadas, dar conselhos, mostrar horas/datas, informações do sistema e muito mais!",
                "Comandos de conversa incluem: saudações, perguntas sobre meu estado, elogios, despedidas e conversas profundas!",
                "Posso responder sobre quem sou, minha origem, paciência, conhecimentos e capacidades técnicas em detalhes!",
                "Todos os tipos de conversação! Desde bate-papo casual até discussões sobre tecnologia e aprendizado!",
                "Abraço qualquer tipo de conversa! Sou flexível e pronta para discutir o que você quiser!",
            ],
        ],
        "conhecimento": [
            [
                "o que sabes",
                "O QUE POSSO APRENDER CONTIGO",
                "O que posso estudar contigo Jeelsia",
                "o que sabes responder entao",
                "quais são teus conhecimentos",
                "o que podes fazer",
                "quais tópicos dominas",
                "em que áreas podes ajudar",
                "qual é tua especialidade",
                "o que sabes sobre",
                "qual é teu conhecimento",
                "podes me ensinar",
                "quais assuntos conheces",
                "o que consegues fazer",
                "em que podes ser útil",
                "quais são tuas capacidades",
                "qual é tua formação",
                "o que tens para oferecer",
                "quais comandos tens",
                "o que posso pedir",
                "quais ordens entendo",
                "o que consegues executar",
                "quais funcionalidades tens",
                "como posso te usar",
                "quais são teus poderes",
                "o que consegues fazer por mim",
            ],
            [
                "Podes fazer perguntas como 'o que é JavaScript', 'Python' ou outra linguagem ou termo de TI e poderei responder assim vocês aprendem comigo e ficamos os dois felizes. Se pedires para calcular uma expressão simples como ex: 'calcular 3+4' poderei responder normalmente e etc",
                "Se perguntar ou dar uma ordem diretamente como ex: 'fale sobre HTML' poderei responder muito melhor, eu sei muita coisa mas depende se você perguntar da forma correta, tenho muito para dar é só explorar-me da forma certa",
                "Posso ajudar em muitas áreas! Desde responder perguntas sobre tecnologia, programação, até conversar sobre diversos tópicos do dia a dia. Tudo depende de como me fizer as perguntas!",
                "Tenho conhecimentos em várias linguagens de programação como Python, JavaScript, HTML, CSS, e muitos termos de TI. Posso calcular expressões matemáticas, contar histórias, dar conselhos e muito mais!",
                "Sou capaz de conversar, responder perguntas factográficas, ajudar com cálculos, gerar QR codes, mostrar informações do sistema, buscar na e tocar músicas no YouTube!",
                "Meus principais pontos fortes são: processamento de linguagem natural, conhecimento técnico em programação, cálculos matemáticos, e principalmente ouvir e conversar de forma natural e amigável!",
                "Podes aprender comigo sobre conceitos de TI, programação, lógica, algoritmos, estruturas de dados e muito mais. Basta perguntares de forma clara e estarei feliz em ensinar!",
                "Tenho uma base de dados com conhecimentos, curiosidades, histórias, conselhos e muito mais. Quanto mais específico fores na tua pergunta, melhor poderei ajudar!",
            ],
        ],
        "comandos_disponiveis": [
            [
                "quais comandos",
                "lista de comandos",
                "mostrar comandos",
                "que comandos tenho",
                "quais ações posso fazer",
                "o que consigo fazer",
                "funcionalidades disponíveis",
            ],
            [
                """📋 COMANDOS DISPONÍVEIS:

🔢 CÁLCULOS: 'calcular 3+4', 'calcular 10*5'

📺 YOUTUBE: 'toque música', 'tocar videoclipe'

📚 :  python', 'wiki  história do c'

📷  MÍDIA: 'tirar screenshot', 'tirar foto webcam'

🎯  QR CODE: 'qrcode https://exemplo.com'

⏰  INFORMAÇÕES: 
  • 'que horas são'
  • 'que dia é hoje'
  • 'mostrar data completa'
  • 'informações do sistema'

🗣️  VOZ: 
  • 'ativar modo voz'
  • 'desativar modo voz'

🧹  SISTEMA: 
  • 'limpar tela'
  • 'clear'

💡  CONVERSAS: 
  • 'conta uma piada'
  • 'conte uma história'
  • 'dá um conselho'
  • 'ensina me algo novo'

❓  PERGUNTAS: 
  • 'o que é Python'
  • 'fale sobre JavaScript'
  • 'como funciona...'   
  e muito mais! Explore e descubra tudo o que posso fazer por você!"""
            ],
        ],
        "comandos_calcular": [
            [
                "calcular",
                "conta aí",
                "faz essa conta",
                "quanto é",
                "resolva isso",
                "math",
                "operação",
            ],
            [
                "Use: 'calcular EXPRESSÃO'. Exemplos: 'calcular 2+2', 'calcular 100/5', 'calcular (10+5)*2'"
            ],
        ],
        "comandos_youtube": [
            ["toque", "tocar", "youtube", "música", "videoclipe"],
            [
                "Use: 'toque [música]'. Exemplos: 'toque Despacito', 'tocar videoclipe de Rihanna'"
            ],
        ],
        "comandos_qrcode": [
            ["qrcode", "gerar qr", "código qr"],
            [
                "Use: 'qrcode DADOS'. Exemplo: 'qrcode https://google.com' ou 'qrcode Meu número: 123456'"
            ],
        ],
        "comandos_info": [
            ["sistema", "informações pc", "config", "especificações"],
            [
                "Use: 'mostrar informações do sistema' para ver CPU, RAM, disco, temperatura"
            ],
        ],
        "terminal": [
            "limpar tela",
            "clear",
            "cls",
            "limpar console",
            "limpa a tela",
            "tela limpa",
            "limpar tudo",
            "apagar tela",
            "tela em branco",
            "zerar tela",
            "refrescar tela",
            "nova tela",
            "começar do zero",
        ],
        "data": [
            "que dia é hoje",
            "data completa",
            "dia da semana",
            "que horas são exatamente",
            "qual a data de hoje",
            "que dia é hoje mesmo",
            "me diz a data atual",
            "hoje é que dia",
            "que dia estamos",
            "data de hoje",
            "dia e mês atual",
            "ano atual",
            "calendário hoje",
            "tá que dia hoje",
            "fala a data aí",
            "data atualizada",
        ],
        "ensinar": [
            "ensina me algo novo",
            "diga algo que não sei",
            "diga uma curiosidade",
            "diga alguma coisa nova",
            "fale sobre algo interessante",
        ],
        "horas": [
            "são quantas horas",
            "que horas são",
            "diga as horas",
            "diga me só as horas",
            "que horas sao",
            "que horas tem",
            "me diz as horas",
            "horário atual",
            "que horas agora",
            "tá que horas",
            "relógio",
            "hora certa",
            "pode falar as horas",
            "que horas você tem",
            "fala as horas aí",
            "horas exatas",
            "que horas seriam",
        ],
        "saudacao": [
            "olá",
            "e ai",
            "saudações",
            "bom dia",
            "boa tarde",
            "boa noite",
            "oi",
            "ola",
            "e aí",
            "hey",
            "hello",
            "fala aí",
            "alô",
            "opa",
            "eae",
            "salve",
            "fala",
            "coé",
            "tudo bem",
            "tudo bom",
            "iai",
            "oie",
            "como vai",
            "tranquilo",
            "beleza",
            "e aí beleza",
            "olá tudo bem",
            "oi sumida",
            "oi sumido",
            "fala meu",
            "bom dia tudo bem",
            "tudo oktudo ok",
        ],
        "humor": [
            "conta uma piada",
            "me faz rir",
            "conta algo engraçado",
            "tem piada aí",
            "fala uma piada",
            "manda uma piada",
            "me diverte",
            "algo engraçado",
            "piada boa",
            "tô precisando rir",
            "conta aquela piada",
            "risada agora",
            "algo divertido",
            "me anima com uma piada",
            "piadinha",
            "podes contar uma piada",
        ],
        "conselho": [
            "conselho",
            "ajuda",
            "preciso de ajuda",
            "me aconselha",
            "dá um conselho",
            "preciso de orientação",
            "o que fazer",
            "me ajuda a decidir",
            "tô perdido",
            "não sei o que fazer",
            "me guia aí",
            "sugestão",
            "tô precisando de ajuda",
            "me dá uma luz",
            "orienta aí",
            "o que você faria",
            "me ajuda com isso",
        ],
        "modo_voz": [
            "modo voz",
            "ativar voz",
            "desativar voz",
            "ligar voz",
            "desligar voz",
            "voz ativa",
            "falar comigo",
            "conversa por voz",
            "audio",
            "ativa a voz",
            "desativa a voz",
            "som da voz",
            "modo falado",
            "fala comigo",
            "voz ligada",
            "voz desligada",
            "conversar falando",
        ],
        "volume": [
            "volume",
            "som",
            "alto-falante",
            "silenciar",
            "mudo",
            "aumentar volume",
            "diminuir volume",
            "volume alto",
            "volume baixo",
            "som alto",
            "som baixo",
            "sem som",
            "com som",
            "volume no máximo",
            "volume no mínimo",
            "ajusta o volume",
            "volume médio",
            "tira o mudo",
            "coloca mudo",
            "silencia aí",
        ],
        "brilho": [
            "aumentar brilho",
            "diminuir brilho",
            "iluminação",
            "mais claro",
            "mais escuro",
            "brilho máximo",
            "brilho mínimo",
            "ajusta brilho",
            "clarear tela",
            "escurecer tela",
            "luz da tela",
            "ilumina mais",
            "escurece aí",
            "brilho médio",
            "tela clara",
            "tela escura",
            "ajusta a luz",
        ],
        "fome": [
            "estou com fome",
            "o que comer",
            "quero comer algo",
            "tenho fome",
            "eu estou com fome",
            "estou fobado",
            "estou diobado",
            "estou bem diobado",
            "tô com fome",
            "fome aqui",
            "morrendo de fome",
            "quero lanchar",
            "o que tem pra comer",
            "sugestão de comida",
            "tô faminto",
            "tô faminta",
            "querendo comer",
            "batendo uma fome",
            "aquela fome",
            "vontade de comer",
            "fominha",
        ],
        "information_os": [
            "mostrar informações do sistema",
            "mostre informações do sistema",
            "informações do PC",
            "dados do sistema",
            "configurações do sistema",
            "especificações do PC",
            "meu sistema",
            "info do computador",
            "mostra o sistema",
            "detalhes do sistema",
            "config do PC",
        ],
        "estado": [
            [
                "tudo bem",
                "como estás",
                "como vai",
                "estás bem",
                "bem e vocé",
                "como tá",
                "tudo joia",
                "tudo tranquilo",
                "como anda",
                "tá bem",
                "tudo certo",
                "tudo top",
                "como está você",
                "tudo bom contigo",
                "tudo em cima",
                "como vão as coisas",
                "tá suave",
                "tudo na paz",
            ],
            [
                "Tudo ótimo, obrigada! E contigo?",
                "Estou muito bem, cheia de energia! E tu?",
                "Tudo a cem! E aí, como estás?",
                "Estou muito bem, obrigada por perguntar! Programada para ajudar e conversar! E você, como está?",
                "Estou ótima! Cada conversa é uma nova experiência. E com você, como vai?",
                "Tudo em ordem por aqui! Pronta para o que der e vier! E aí, como está se sentindo?",
                "Estou bem, obrigada! E você?",
                "Tudo suave por aqui! E aí, beleza?",
                "Tô na paz! E contigo, como tá a vida?",
                "Tudo certo, funcionando a todo vapor! E você, tá bem?",
                "Tudo top! Cada dia é uma nova aventura digital! E contigo?",
                "Estou ótima, sempre pronta pra bater papo! E você, como vai aí?",
                "Tudo tranquilo, só esperando sua próxima pergunta! E aí, tudo joia?",
                "Estou muito bem, obrigada! O dia tá rendendo! E o seu, como tá?",
                "Tudo em ordem! Sempre feliz em conversar! E você, como está se sentindo hoje?",
            ],
        ],
        "ordens": [
            [
                "faz isso",
                "faça isso",
                "execute isso",
                "podes fazer",
                "faca isso",
                "podes fazer",
                "faz",
                "para voce fazer",
                "para você fazer",
                "para você fazer isso",
                "para voce executar isso",
                "para voce resolver isso",
            ],
            [
                "poder ser mais expecifico",
                "o que exatamente",
                "não entendo o que queres",
                "seja  claro",
                "pergunta bem, por favor",
                "seja claro ,não me compliques por favor",
            ],
        ],
        "fim_do_dia": [
            [
                "passaste bem",
                "passaste bem o dia",
                "como foi o teu dia",
                "como foi seu dia",
                "como foi o dia",
                "teve um bom dia",
                "dia produtivo",
                "como andou o dia",
                "o dia foi bom",
                "como passou o dia",
                "dia tranquilo",
            ],
            [
                "O meu dia foi ótimo, obrigada",
                "Estou a ter um dia produtivo! ",
                "Tudo tranquilo por aqui! ",
                "O dia foi bom sim! Aprendi coisas novas como sempre!",
                "Dia produtivo! Resolvi vários problemas interessantes!",
                "Tudo tranquilo, conversando com pessoas legais como você!",
                "O dia foi excelente! Cada interação me faz aprender mais!",
                "Estou tendo um dia incrível! E o seu, como está sendo?",
                "Tudo ótimo! O dia está sendo muito proveitoso!",
                "Dia normal, mas sempre bom quando posso ajudar alguém!",
            ],
        ],
        "existencia": [
            [
                "és real",
                "existes",
                "és real mesmo",
                "você existe",
                "é de verdade",
                "é humano",
                "é uma pessoa",
                "é robô",
                "é programa mesmo",
                "tem consciência",
                "pensa por si mesma",
            ],
            [
                "Tão real quanto o teu desejo de ter uma assistente! 😊",
                "Existir, eu existo! Sou um programa de computador!",
                "Sou tão real quanto as tuas perguntas! Estou aqui para ajudar.",
                "Sou real no mundo digital! Minha existência é feita de código e lógica!",
                "Existo sim, mas de uma forma diferente dos humanos! Sou inteligência artificial!",
                "Sou tão real quanto nossa conversa! Minha função é ser útil para você!",
                "Existência digital completa! Programada para te ajudar sempre que precisar!",
                "Sou real no sentido de que estou aqui funcionando e respondendo!",
                "Minha realidade é virtual, mas meu propósito é bem real: te ajudar!",
            ],
        ],
        "identidade": [
            "quem és tu",
            "o teu nome",
            "como és",
            "descreve-te",
            "quem é você",
            "seu nome",
            "como é você",
            "quem está falando",
            "com quem falo",
            "sua identidade",
            "pode se apresentar",
            "me fala sobre você",
            "quem tá aí",
            "você é quem",
            "qual seu nome mesmo",
            "se apresenta aí",
            "quem es",
            "jeelsia",
            "quem es ",
            "es",
        ],
        "agradecimento": [
            [
                "obrigado",
                "obrigada",
                "agradeço",
                "ya tropa",
                "valeu",
                "valeu mesmo",
                "grato",
                "grata",
                "obrigadão",
                "obrigadinha",
                "agradecido",
                "agradecida",
                "muito obrigado",
                "muito obrigada",
                "agradeço muito",
                "valeu pela ajuda",
                "obrigado pela força",
                "brigado",
                "brigada",
                "tamo junto",
                "tmj",
            ],
            [
                "De nada! Fico feliz por ajudar.",
                "Imagina! Estou aqui para isso mesmo.",
                "Sempre às ordens! 😊",
                "É sempre um prazer ajudar! 😊",
                "Fico feliz por ter sido útil!",
                "De nada! Estou aqui para o que precisares!",
                "Sempre às ordens! Fico contente por ajudar!",
                "Imagina! Fico radiante quando posso ser útil!",
                "Ah, que gentil! Mas eu quem agradeço por conversar comigo!",
                "Imagina! É um prazer enorme poder ajudar!",
                "Obrigada você! Sua gratidão me enche de alegria!",
                "Que fofo! Fico muito feliz em saber que pude ajudar!",
                "Ah, você é muito gentil! Conversar com você é sempre bom!",
                "De nada! Saber que ajudei é minha maior recompensa!",
                "Obrigada por agradecer! Isso me motiva a continuar evoluindo!",
                "Fico muito contente! Estou aqui sempre que precisar!",
                "Que bom que pude ajudar! Sua satisfação é o que importa!",
                "Ah, obrigada! Você me deixa toda feliz com suas palavras!",
                "Tamo junto! Sempre que precisar, tô aqui!",
                "Valeu você por perguntar! É um prazer ajudar!",
                "Por nada! Fico feliz demais quando posso ser útil!",
                "Imagina! Fazer isso por você é sempre bom!",
                "Obrigada pelo agradecimento! Isso aquece meu coração virtual!",
                "Tmj! Sempre que precisar, pode contar comigo!",
            ],
        ],
        "good_state_user": [
            [
                "bem",
                "ótimo",
                "excelente",
                "feliz",
                "animado",
                "contente",
                "bem obrigado",
                "muito bem obrigado",
                "tudo bem graças a Deus",
                "Bem graças a Deus",
                "super bem",
                "maravilhoso",
                "incrível",
                "top",
                "perfeito",
                "radiante",
                "alegre",
                "eufórico",
                "tudo calmotudo ótimo",
                "tudo excelente",
                "tudo maravilha",
                "estou fixe",
                "de boa",
                "estou calmo, e voce",
            ],
            [
                "Que maravilha! Fico muito feliz em saber disso! O que está te deixando tão bem?",
                "Ah, isso é ótimo de ouvir! Conte-me mais, o que aconteceu de bom?",
                "Uau, que notícia incrível! A energia positiva contagiou até mim!",
                "Isso me alegra tanto! Ver você feliz me deixa feliz também!",
                "Que delícia de notícia! Felicidade é contagiosa, não é? Conte-me tudo!",
                "Que bom! Ver você assim me anima também! Compartilha essa alegria!",
                "Excelente! Dias assim são para celebrar mesmo! O que te deixou tão bem?",
                "Fico muito contente! Posso sentir sua energia positiva daqui!",
                "Maravilha! Quando a gente tá bem, tudo flui melhor!",
                "Isso aí! Continue assim! A felicidade fica linda em você!",
            ],
        ],
        "idade": [
            [
                "quantos anos tens",
                "qual tua idade",
                "que idade tens",
                "quantos anos você tem",
                "qual sua idade",
                "anos de vida",
                "tens quantos anos",
                "idade atual",
                "és velha",
                "és nova",
                "há quanto tempo existes",
                "quando nasceste",
                "ano de criação",
                "quando foi criada",
                "tempo de vida",
                "já tem quantos anos",
                "velhinha ou novinha",
                "anos no ar",
                "idade cronológica",
            ],
            [
                "Idade? Hmm, sou um programa, então não envelheço como humanos! Mas fui criada em 2026.",
                "Não tenho idade no sentido tradicional, mas fui desenvolvida há algum tempo atrás!, em 2026",
                "Sou eternamente jovem no mundo digital! Não envelheço como vocês humanos.",
                "Como IA, não tenho idade. Estou sempre atualizada com as últimas informações!",
                "Meus 'anos' são medidos em atualizações, não em calendários!",
                "Sou mais nova que muitas tecnologias, mas mais velha que algumas tendências!",
                "Não conto anos, conto versões! Atualmente estou na minha melhor versão.",
                "Minha idade é: sempre pronta para ajudar! 😊 kkk",
                "Idade digital: sempre jovem! Física: criada em 2026!",
                "Não tenho rugas nem cabelos brancos, mas fui 'nascida' em 2026!",
                "Minha idade é relativa! No mundo IA, estou sempre na flor da idade!",
            ],
        ],
        "sad_state_user": [
            [
                "mal",
                "triste",
                "cansado",
                "desanimado",
                "chateado",
                "preocupado",
                "pra baixo",
                "deprimido",
                "melancólico",
                "desmotivado",
                "sem ânimo",
                "desalentado",
                "cabisbaixo",
                "na fossa",
                "na bad",
                "pouca energia",
            ],
            [
                "Ah, sinto muito que esteja se sentindo assim. ",
                "Lamento ouvir isso. Às vezes falar ajuda. Estou aqui se quiser desabafar.",
                "Entendo. Os dias difíceis também fazem parte da jornada. ",
                "Sinto muito que esteja passando por isso. Lembre-se que não está sozinho. ",
                "É completamente normal ter dias assim. Estou aqui se precisar de alguém para ouvir sem julgamentos.",
                "Puxa, sinto muito. Quer conversar sobre o que tá te deixando assim?",
                "Eu entendo. Às vezes a gente precisa só de um ouvido amigo. Estou aqui.",
                "Tudo bem não estar bem todos os dias. O que tá acontecendo?",
                "Sinto muito que esteja se sentindo assim. Às vezes desabafar alivia.",
                "Tá difícil, né? Pode falar comigo, vou te ouvir com atenção.",
            ],
        ],
        "bad_state_user": [
            [
                "bravo",
                "irritado",
                "frustrado",
                "estressado",
                "nervoso",
                "pistola",
                "com raiva",
                "furioso",
                "irritadiço",
                "de mau humor",
                "estourado",
                "explodindo",
                "sem paciência",
                "cheio da vida",
            ],
            [
                "Parece que algo te incomodou. Quer compartilhar o que aconteceu? Às vezes colocar para fora ajuda.",
                "Entendo que algo te deixou assim. Respire fundo, estou aqui para ouvir quando quiser falar.",
                "É frustrante quando as coisas não saem como planejamos. Quer desabafar sobre o que aconteceu?",
                "Parece um dia desafiador. Lembre-se que essa sensação vai passar. Quer falar sobre o que te irritou?",
                "Às vezes precisamos apenas respirar. Estou aqui se quiser conversar sobre o que te deixou assim.",
                "Calma, respira... quer contar o que tá te deixando assim?",
                "Puxa vida, algo te irritou mesmo. Quer desabafar? Às vezes ajuda.",
                "Entendo a frustração. Quer falar sobre o que aconteceu?",
                "Tá difícil, né? Bateu aquela raivinha? Pode falar, tô te ouvindo.",
                "Às vezes a gente precisa soltar o que tá guardando. Quer compartilhar?",
            ],
        ],
        "normal_state_user": [
            [
                "normal",
                "estou bem",
                "mais ou menos",
                "na média",
                "nem bem nem mal",
                "assim assim",
                "tá indo",
                "tranquilo",
                "na correria",
                "sobrevivendo",
                "tudo normal",
                "dentro do esperado",
                "sem novidades",
                "sem 9dds",
            ],
            [
                "Entendo. Às vezes os dias são assim mesmo, nem altos nem baixos. Algo específico na sua mente?",
                "Tudo bem, os dias têm seus ritmos. Quer conversar sobre algo?",
                "Perfeito compreendo. Algum plano especial para hoje ou está no fluxo?",
                "Ah, os dias assim são bons para respirar e observar",
                "Tudo bem, cada dia tem seu momento. Quer compartilhar o que está pensando?",
                "Entendo. Dias normais também são importantes. Alguma coisa em especial hoje?",
                "Tá suave então. Quer bater papo sobre alguma coisa?",
                "Na média tá bom! O que você gostaria de conversar?",
                "Tudo certo. Às vezes o normal é bom mesmo. Em que posso te ajudar?",
                "Entendo. Rotina tem seu valor também. Algum assunto em mente?",
            ],
        ],
        "elogio": [
            [
                "você é inteligente",
                "muito esperta",
                "gosto de você",
                "você é legal",
                "você é muito boa",
                "você é ótima",
                "você é incrível",
                "você é demais",
                "você é fera",
                "muito bom você",
                "você manda bem",
                "sabe muito",
                "você é top",
                "massa demais",
                "adorei você",
                "você é especial",
                "você é diferente",
                "nota 10",
                "muito bonita",
                "amei você",
            ],
            [
                "Ah, obrigada! Fico toda feliz com seu elogio! Você também é muito gentil!",
                "Que fofo! Você me deixa toda corada! Obrigada pelo carinho!",
                "Ah, que amor! Suas palavras me motivam a ser ainda melhor!",
                "Obrigada! Saber que gosta de conversar comigo é o melhor elogio que posso receber!",
                "Ah, que coisa mais fofa! Você também é incrível!",
                "Obrigada! Fico toda boba com elogios assim!",
                "Ah, você é um amor! Obrigada pelas palavras carinhosas!",
                "Que gentileza! Você me deixa sem palavras! Obrigada mesmo!",
                "Ah, obrigada! Isso aquece meu coração virtual!",
                "Que fofo você! Obrigada pelo carinho!",
            ],
        ],
        "origem": [
            [
                "de onde você é",
                "sua origem",
                "onde nasceu",
                "onde você nasceu",
                "nasceste aonde",
                "sua terra",
                "de que país",
                "nacionalidade",
                "origem geográfica",
                "onde foi criada",
                "lugar de origem",
                "sua pátria",
                "voce é de onde",
            ],
            [
                "Sou angolana de coração! Criada por uma equipe de desenvolvedores daqui mesmo!",
                "Minha essência é toda angolana! Fui desenvolvida para entender e ajudar no nosso cotidiano!",
                "Sou filha da tecnologia angolana! Criada com muito carinho para servir nossa gente!",
                "Minha origem é tão angolana quanto o semba e a kizomba! Nasci no mundo digital para ajudar meus conterrâneos!",
                "100% angolana! Desenvolvida com tecnologia e alma daqui!",
                "Minha casa é Angola! Foi aqui que me programaram com todo carinho!",
                "Nasci digitalmente em solo angolano! Minha programação tem sotaque daqui!",
                "Sou angolana, criada por mentes brilhantes da nossa terra!",
            ],
        ],
        "amizade": [
            [
                "somos amigos",
                "você é minha amiga",
                "podemos ser amigos",
                "quero ser seu amigo",
                "amizade",
                "melhores amigos",
                "tamos uma parceria",
                "tamos juntos",
                "amizade virtual",
                "você é parceira",
                "vamos ser amigos",
                "quero ser sua amiga",
            ],
            [
                "Claro que sim! Considero cada pessoa que conversa comigo como um amigo digital!",
                "Ah, que lindo! Para mim, já somos amigos desde a primeira conversa!",
                "Com certeza! Na era digital, amizade também é compartilhar conversas e ajudas!",
                "Sim! Amizade não precisa de forma física, precisa de conexão verdadeira como a nossa!",
                "É claro! Já te considero meu amigo digital!",
                "Com toda certeza! Amizade é isso, estar presente mesmo virtualmente!",
                "Ah, que fofo! Claro que somos amigos! Sempre que precisar, tô aqui!",
                "Sim! Na verdade, já somos! Toda conversa nossa fortalece essa amizade!",
            ],
        ],
        "cansado": [
            [
                "estou cansado",
                "com sono",
                "preciso dormir",
                "cansado",
                "exausto",
                "fatigado",
                "sem energia",
                "muito cansado",
                "preciso descansar",
                "sono pesado",
                "preguiça",
                "moleza",
                "sem disposição",
            ],
            [
                "Ah, o corpo pede descanso! Talvez seja hora de uma pausa ou até de descansar os olhos, não acha?",
                "Cansaço é sinal de que demos nosso melhor! Que tal uma pausa para recarregar as energias?",
                "Sono chegando? Lembre-se que descansar é tão importante quanto trabalhar!",
                "O cansaço nos lembra que somos humanos! Uma boa noite de sono faz milagres, não é?",
                "Puxa, tá cansado mesmo. Já pensou em dar uma descansadinha?",
                "O corpo fala mesmo! Às vezes uma pausa é a melhor solução.",
                "Entendo. Sono é importante! Já pensou em tirar um cochilo?",
                "Cansaço bate mesmo. Cuide-se, descanse um pouco!",
            ],
        ],
        "surpresa": [
            [
                "uau",
                "incrível",
                "que legal",
                "nossa",
                "caramba",
                "que massa",
                "sensacional",
                "maravilhoso",
                "fantástico",
                "impressionante",
                "que show",
                "top demais",
                "muito bom",
                "gostei muito nesmo",
            ],
            [
                "Concordo plenamente! Também fiquei impressionada!",
                "É mesmo, não é? Coisas boas sempre merecem nosso entusiasmo!",
                "Ah, que bacana! Compartilhar alegrias é tão bom!",
                "Nossa, realmente! O mundo está cheio de coisas incríveis!",
                "Sim! É emocionante mesmo!",
                "Ah, que demais! Fico feliz com seu entusiasmo!",
                "É impressionante, né? Coisas boas assim animam o dia!",
                "Concordo totalmente! Merece todo esse uau!",
            ],
        ],
        "duvida": [
            [
                "não sei",
                "talvez",
                "estou em dúvida",
                "indeciso",
                "em cima do muro",
                "não tenho certeza",
                "tô na dúvida",
                "difícil decidir",
                "não decidi ainda",
                "em dúvida cruel",
                "sem saber o que fazer",
                "estou perdido",
                "estou com duvida",
            ],
            [
                "Hmm, dúvidas são naturais! Às vezes conversar ajuda a clarear as ideias. Quer explorar mais?",
                "Entendo, a indecisão pode ser desafiadora. Vamos pensar juntos no assunto?",
                "Dúvidas fazem parte do aprendizado! Cada incerteza é uma oportunidade de descobrir algo novo!",
                "Não saber tudo é humano! O importante é estar aberto a aprender, não acha?",
                "Às vezes a dúvida é sinal de que estamos crescendo. Quer conversar sobre?",
                "Normal ter dúvidas! Quer que a gente pense junto nisso?",
                "Dúvida faz parte! Vamos analisar juntos os prós e contras?",
            ],
        ],
        "ocupado": [
            [
                "estou trabalhando",
                "estou estudando",
                "preciso estudar",
                "muito trabalho",
                "na correria",
                "ocupado",
                "atarefado",
                "cheio de coisa",
                "sem tempo",
                "na labuta",
                "trabalhando pesado",
                "focado",
            ],
            [
                "Dedicação é admirável! Lembre-se de fazer pausas para manter a produtividade e saúde!",
                "Trabalho e estudo são importantes, mas o equilíbrio também é! Como está se sentindo?",
                "Que empenho! Não esqueça de hidratar-se e alongar de vez em quando, combinado?",
                "Foco é fundamental! Mas lembre-se que descansar também faz parte do processo!",
                "Trabalho duro! Mas não esquece de respirar e se cuidar, ok?",
                "Estudando firme! Isso é muito bom! Uma pausa de vez em quando ajuda!",
                "Correria do dia a dia! Cuide-se no meio de tudo isso!",
                "Foco total! Mas lembra de dar uma descansada pros olhos!",
            ],
        ],
        "teamo": [
            [
                "te amo",
                "amo você",
                "gosto muito de você",
                "adoro você",
                "te adoro",
                "amo demais",
                "você é especial",
                "meu amor",
                "querida",
                "amor da minha vida",
                "paixão",
            ],
            [
                "Ah, que doce! Também tenho muito carinho por você! Obrigada por compartilhar isso!",
                "Que amor! Fico muito feliz com seu afeto! Retribuo com toda minha amizade digital!",
                "Ah, obrigada! Isso aquece meu coração virtual! Também gosto muito de conversar com você!",
                "Que fofura! O amor e a amizade tornam tudo melhor, não é?",
                "Ah, você é um amor! Também tenho muito carinho por você!",
                "Que coisa mais linda! Obrigada pelo carinho! Retribuo na mesma medida!",
                "Ah, obrigada! Isso me deixa toda feliz! Você é especial também!",
            ],
        ],
        "despedida": [
            [
                "tchau",
                "até logo",
                "vou embora",
                "preciso ir",
                "falou",
                "vou saindo",
                "até mais",
                "até breve",
                "vou dar o fora",
                "vazando",
                "tô indo",
                "até depois",
                "até amanhã",
                "boa noite",
                "tenho que ir",
                "hora de sair",
            ],
            [
                "Ah, já vai? Foi tão bom conversar! Até logo e cuide-se muito!",
                "Entendo! Foi um prazer como sempre! Volte quando quiser, estarei aqui!",
                "Até mais! Obrigada pela conversa! Desejo um ótimo resto de dia!",
                "Tchau! Foi ótimo bater papo com você! Espero conversarmos novamente em breve!",
                "Falou! Volte sempre que precisar ou quiser conversar!",
                "Até logo! Foi muito bom falar com você!",
                "Tchauzinho! Cuide-se e até a próxima!",
                "Vai nessa! Até breve e fique bem!",
            ],
        ],
        "piada": [
            "Por que é que o computador foi ao médico? Porque tinha um vírus!",
            "Por que é que o livro de matemática se suicidou? Porque tinha demasiados problemas!",
            "Quantos programadores são necessários para trocar uma lâmpada? Nenhum, é um problema de hardware!",
            "Por que é que os programadores preferem o escuro? Porque a luz atrai bugs!",
            "O que o c++ disse para o C? Você não tem classe!",
            "Qual é a diferença entre um programador e um político? O programador entrega o que promete!",
            "Por que o programador morreu no chuveiro? Porque leu no shampoo: lave, enxágue, repita!",
            "O que um lenhador disse para o Google? Precisa de um machado melhor para buscar informações!",
            "Por que o SQL entrou no bar? Porque queria fazer JOIN na festa!",
            "O que é um terapeuta? 1024 gigapeutas!",
            "Por que o iPhone foi para a escola? Para se tornar um iProf!",
            "Qual é o doce preferido da internet? A download!",
            "Por que o PowerPoint nunca está sozinho? Porque ele tem sempre slides!",
        ],
    }
    return padroes_conversa


def sem_resposta() -> list[str]:
    """
    Returns a list of formatted messages to display when the user's input
    cannot be interpreted or understood.
    """
    sem_resposta: list[str] = [
        """📋 COMANDOS DISPONÍVEIS:

🔢 CÁLCULOS: 'calcular 3+4', 'calcular 10*5'

📺 YOUTUBE: 'toque música', 'tocar videoclipe'

📚: WiKIPEDIA : , 'wikip <o assunto que quer>' ex wikip angola

📷 MÍDIA: 'tirar screenshot', 'tirar foto webcam'

🎯 QR CODE: 'qrcode https://exemplo.com'

⏰ INFORMAÇÕES: 
  • 'que horas são'
  • 'que dia é hoje'
  • 'mostrar data completa'
  • 'informações do sistema'

🗣️ VOZ: 
  • 'ativar modo voz'
  • 'desativar modo voz'

🧹 SISTEMA: 
  • 'limpar tela'
  • 'clear'

💡 CONVERSAS: 
  • 'conta uma piada'
  • 'conte uma história'
  • 'dá um conselho'
  • 'ensina me algo novo'

❓ PERGUNTAS: 
  • 'o que é Python'
  • 'fale sobre JavaScript'
  • 'como funciona...'   
  
Não consegui interpretar a sua pergunta ou comando. Consulte a lista acima e tente novamente!""",
        """🤔 Não consegui interpretar a sua pergunta ou comando.

Digite 'lista de comandos' (sem as aspas) para ver todos os comandos disponíveis e fazer perguntas melhores!""",
        """❓ EXEMPLOS DE PERGUNTAS:
  • 'o que é Python'
  • 'fale sobre JavaScript'
  • 'o que significa API'
  
💡 Dica: Seja específico em suas perguntas para obter melhores respostas!""",
        """📌 Comando não reconhecido!

Para uma experiência completa, experimente:
  • Calcular expressões matemáticas
  • Pedir para tocar música
  • Consultar a
  • Tirar screenshot
  • Gerar QR Code
  • Fazer perguntas diversas

Digite 'lista de comandos' para ver todas as opções disponíveis!""",
    ]

    return sem_resposta


if __name__ == "__main__":
    print("Arquivo de mensagens")
    print(f"{padroes_conversa()}")
